//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [Range(1, 1000)]
        public int PetID { get; set; }
        [StringLength(30)]
        public string PetName { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public int OwnerID { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
