CREATE TABLE [dbo].[Pet]
(
	[PetID] INT,
	[PetName] CHAR(20) NOT NULL,
	[Type] CHAR(20) NOT NULL,
	[OwnerID] INT NOT NULL
	CONSTRAINT [PK_PET] PRIMARY KEY ([PetID]),
	CONSTRAINT [FK_PETOWNER] FOREIGN KEY ([OwnerID]) REFERENCES [Owner] ([OwnerID])
)
